catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    # including 'django.contrib.auth.urls' includes:
    # accounts/login/ [name='login'], accounts/logout/ [name='logout']
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

# Prefer convention over configuration
urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('cats/', views.cats_index, name="index"),
    path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
    path('cats/<int:cat_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('cats/<int:cat_id>/add_photo/', views.add_photo, name='add_photo'),
    path('cats/create/', views.CatCreate.as_view(), name='cats_create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
    path('cats/<int:cat_id>/add_toy/<int:toy_id>/', views.add_toy, name='add_toy'), 
    path('cats/<int:cat_id>/remove_toy/<int:toy_id>/', views.remove_toy, name='remove_toy'), 

    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),

    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

#  A tuple of 2-tuples, we use tuple because we dont change the data in it 
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)

 
class Toy(models.Model):
    name = models.CharField(max_length=256)
    color = models.CharField(max_length=16)

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id }) # pk is equal to toy.id, Django prefers pk
    
    def __str__(self):
        return self.name

# Create your models here.
# Models are entities in ERD
class Cat(models.Model):
    #get translated as Db Table rows
    name = models.CharField(max_length=256)
    breed = models.CharField(max_length=256)
    description = models.TextField(max_length=256)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)
    # add user_id FK column
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
       return self.name
    
    # url method that we use in base.html is a DTL and 
    # we dont model doesnt have access to it so we use rerverse method
    # Django magic to get the URL by examining the corresoponding path()
    # in simple word, go back to detail url and replace cat_id with self.id
    def get_absolute_url(self):
        return reverse('detail', kwargs={'cat_id': self.id})
    
# we have to define Cat model before Feedin model
class Feeding(models.Model):
      # the first optional positional argument overrides the label 'date'
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1, #max_length=len('Breakfast')
        choices = MEALS,
        default = MEALS[0][0]
    )
    # we want deleting a cat will delete its associated data in join  table as well
    # for example if delete a cat before deleting its Feedings without CASCADE , we get error
    # In 1:M we do this in child, and in M:M we do it in one of the models, no defrence
    cat = models.ForeignKey(Cat, on_delete = models.CASCADE)


    # get_meal_display is a Django function that get meal as tuple and 
    # returns the value for 'B' which is 'Breakfast' in the 2-tuple
    def __str__(self):
        return f"{ self.get_meal_display() } on { self.date }"
    
    class Meta:
        ordering = ['-date'] # order feeding from most recent to least
    

class Photo(models.Model):
    url = models.CharField(max_length=200)
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__ (self):
        return f"Photo for cat_id: {self.cat_id} @{self.url}"



        

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
import os
import uuid
import boto3

from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Cat, Toy, Photo

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse

from .forms import FeedingForm



# Create your views here.
def home(request):
   return render(request, 'home.html')

def about(request):
   return render(request, 'about.html')

@login_required
def cats_index(request):
   cats = Cat.objects.filter(user=request.user)
   #Another Query
   # cats = request.user.cat_set.all()
   return render(request, 'cats/index.html', {
      'cats': cats
   })

@login_required
def cats_detail(request, cat_id):
   cat = Cat.objects.get(id=cat_id)
   feeding_form = FeedingForm()
   current_toy_ids = cat.toys.all().values_list('id')
   available_toys = Toy.objects.exclude(id__in=current_toy_ids)
   return render(request, 'cats/detail.html', {
      'cat': cat, 
      'feeding_form': feeding_form,
      'available_toys': available_toys,
   })
@login_required
def add_feeding(request, cat_id):
   feeding_form = FeedingForm(request.POST) # request.POST is equivalent for req.body
   if feeding_form.is_valid():
      new_feeding = feeding_form.save(commit=False)
      new_feeding.cat_id = cat_id
      new_feeding.save()
   return redirect('detail', cat_id=cat_id)
      


 
#GET/ /cats/create AND POST /cats/create
# CatCreate class inherit from two super class LoginRequiredMixin and CreateView
# inheriting from superclass LoginRequiredMixin protects class-based views
class CatCreate(LoginRequiredMixin, CreateView):
   model = Cat
   fields = ['name', 'breed', 'description', 'age']
    # Dont handle toys in create

   #we want only authenticated user be able to create cat
   def form_valid(self, form):
      # self.request.user is the logged user, remeber user object is available when we login
      form.instance.user = self.request.user
      # let the CreateView's form_valid method
      #do its regular work which is saving the model in DB & redirect
      return super().form_valid(form)
   

class CatUpdate(LoginRequiredMixin, UpdateView):
   model = Cat
   fields = ['breed', 'description', 'age']

class CatDelete(LoginRequiredMixin, DeleteView):
   model = Cat
   success_url = '/cats/' #TODO get reverse function work

# Toy CRUD ###############################

class ToyList(LoginRequiredMixin, ListView):
   model = Toy

class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy

class ToyCreate(LoginRequiredMixin, CreateView):
   model = Toy
   fields = '__all__'

class ToyUpdate(LoginRequiredMixin, UpdateView):
   model = Toy
   fields = '__all__'

class ToyDelete(LoginRequiredMixin, DeleteView):
   model = Toy
   success_url = '/toys/' #TODO: dont hardcode ---use Reverse

@login_required
def add_toy(request, cat_id, toy_id):
   Cat.objects.get(id=cat_id).toys.add(toy_id)
   return redirect('detail', cat_id=cat_id)
@login_required
def remove_toy(request, cat_id, toy_id):
   Cat.objects.get(id=cat_id).toys.remove(toy_id)
   return redirect('detail', cat_id=cat_id)


######## Photo CRUD #############
@login_required
def add_photo(request, cat_id):
   photo_file = request.FILES.get('photo-file', None)
   if photo_file:
      s3 = boto3.client('s3')
      # Need a unique 'key' (filename)
      # It needs to keep the same file extension
      # of the file that was uploaded(.png, .jpeg, etc)
      # First part of this command generate a unique identifier +
      # and second part finds the . in the file name(ex: cat01.png and slice .png using : until the end)
      key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
      try:
         bucket = os.environ['S3_BUCKET']
         s3.upload_fileobj(photo_file, bucket, key)
         #Build the full url string
         url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
         Photo.objects.create(url=url, cat_id=cat_id)
      except Exception as e:
         print('An error occurred uploading file to S3')
         print(e)
   return redirect('detail', cat_id=cat_id)


def signup(request):
   error_message = ''
   if request.method == 'POST':
      form = UserCreationForm(request.POST)
      if form.is_valid():
         # save the user in DB
         user = form.save()
         # Authomatically log in the new user
         login(request, user)
         return redirect('index') # redirect send a GET request
      else:
         error_message = 'Invalid sign up - try again'
    #  # A bad POST or a GET request, so render signup.html with an empty form
   form = UserCreationForm()
   context = {'form': form, 'error_message': error_message}
   return render(request, 'registration/signup.html', context)
()

main_app/templates/cats/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Cat Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cat.name }}</span>
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description|linebreaksbr }}</p>
        {% if cat.age > 0 %}
          <p>Age: {{ cat.age }}</p>
        {% else %}
          <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'cats_update' cat.id %}">Edit Cat</a>
        <a href="{% url 'cats_delete' cat.id %}">Delete Cat</a>
      </div>
    </div>
    {% for photo in cat.photo_set.all %}
      <img class="responsive-img card-panel" src="{{ photo.url }}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' cat.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <button type="submit" class="btn">Upload Photo</button>
  </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' cat.id %}" method="post">
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in cat.feeding_set.all %}
          <tr>
            <td>{{ feeding.date }}</td>
            <td>{{ feeding.get_meal_display }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>

<div class="row">
  <div class="col s6">
    <h3>{{ cat.name }}'s Toys</h3>
    {% if cat.toys.count %}
      {% for toy in cat.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'remove_toy' cat.id toy.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
        <h4>No Toys</h4>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if available_toys.count %}
      {% for toy in available_toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'add_toy' cat.id toy.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
        <h4>
          {{ cat.name }} already has all toys available.
        </h4>
    {% endif %}    
  </div>
</div>

<script>
const dateElement = document.getElementById('id_date');
M.Datepicker.init(dateElement, {
  format: 'yyyy-mm-dd',
  defaultDate: new Date(),
  setDefaultDate: true,
  autoClose: true
});

const selectElement = document.getElementById('id_meal');
M.FormSelect.init(selectElement);
</script>

{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Cat List</h1>

{% for cat in cats %}
<!-- Exactly same as <a href="/cats/{{ cat.id }}"> -->
<a href="{% url 'detail' cat.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ cat.name }}</span>
      <p>Breed: {{ cat.breed }}</p>
      <p>Description: {{ cat.description }}</p>
      {% if cat.age > 0 %}
        <p>Age: {{ cat.age }}</p>
      {% else %}
        <p>Age: Kitten</p>
      {% endif %}
    </div>
  </div>
</a>
{% endfor %}

{% endblock %}